name: Publish Beta Package

on:
  workflow_dispatch:
    branches:
      - beta

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: Beta
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: beta

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

      - name: Build and publish
        run: |
          npm publish --tag beta
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
